import { GEN_MODULES } from './_common';

export const GEN_AUTHORITIES = {
  CODE: GEN_MODULES.CODE,
  ADMIN: `${GEN_MODULES.CODE}001`,
  SECURITY: {
    ADMIN: `${GEN_MODULES.SUBS.SECURITY}001`,
  },
  AUTHORITIES: {
    CODE: GEN_MODULES.SUBS.AUTHORITIES,
    MANAGE_ALL_AUTHORITIES: `${GEN_MODULES.SUBS.AUTHORITIES}001`,
    CREATE_AUTHORITIES: `${GEN_MODULES.SUBS.AUTHORITIES}002`,
  },
  CHAT: {
    CODE: GEN_MODULES.SUBS.CHAT,
    RELACIONES_CHAT_USUARIO: `${GEN_MODULES.SUBS.CHAT}001`,
    RELACIONES_CHAT_PACIENTE: `${GEN_MODULES.SUBS.CHAT}002`,
    RELACIONES_CHAT_ALL: `${GEN_MODULES.SUBS.CHAT}003`,
  },
  PACIENTES: {
    CODE: GEN_MODULES.SUBS.PACIENTES,
    HABILITAR_PACIENTE_APP: `${GEN_MODULES.SUBS.PACIENTES}001`,
    ADD_PACIENTE_TO_AREA: `${GEN_MODULES.SUBS.PACIENTES}001`,
  },
  EVENTOS: {
    CODE: GEN_MODULES.SUBS.EVENTOS,
    ADD_EVENTOS_PACIENTES: `${GEN_MODULES.SUBS.EVENTOS}001`,
  },
};
